#!/usr/bin/env python
#
# Copyright (C) 2019 @alanndz (Telegram and Github)
# SPDX-License-Identifier: GPL-3.0-or-later

import sys, getopt, os, subprocess

cwd = os.getcwd()
config = os.path.join(cwd, 'config')

def sh(cmd, input="", cwd=cwd, silence = False):
    rst = subprocess.run(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, input=input.encode("utf-8"), cwd=cwd)
    assert rst.returncode == 0, rst.stderr.decode("utf-8")
    if silence:
        return rst.stdout.decode("utf-8")
    return print (rst.stdout.decode("utf-8"))

class Main:
    def __init__(a, argv):

        unixOpt = "hnu:r:sl"
        gnuOpt = ["new", "update=",
                 "release=", "switch",
                 "list"]
        try:
            opts, args = getopt.getopt(argv, unixOpt, gnuOpt)
        except getopt.GetoptError as err:
            print (str(err))
            sys.exit(2)
        for opt, arg in opts:
            if opt == '-h':
                print ('test.py -i <inputfile> -o <outputfile>')
                sys.exit()
            elif opt in ("-n", "--new"):
                a.new()
            elif opt in ("-u", "--update"):
                l = a.list()
                if not arg in l:
                    print ('Your value is not exist or not availabe, check use -l or --list')
                    sys.exit()
                a.update(arg)
            elif opt in ("-r", "--release"):
                a.release(arg)
            elif opt in ("-s", "--switch"):
                a.switch()
            elif opt in ("-l", "--list"):
                print ('List: \n')
                l = a.list()
                for i in l: print (i)


    def new(a):
        while 1:
            fol = input('Enter a folder/name: ')
            if fol: break
        try:
            os.mkdir(os.path.join(config, fol))
        except OSError:
            print ('Creation folder error, exit')
            sys.exit()
        else:
            print ('Creation foler %s Success, next' % fol)
        folder = os.path.join(config, fol)
        open(os.path.join(config, 'folder'), 'w').write(fol)
        a.writeConfig(folder, 'Codename', 'codename')
        a.writeConfig(folder, 'Branch', 'branch')
        print ('Release Kernel? \n\n[1] False \n[2] True \n')
        while 1:
            i = input('Enter a Value: ')
            i = int(i)-1
            if i == 0 or i == 1: break
        open(os.path.join(folder, 'release'), 'w').write(str(i))
        while 1:
            i = input('Enter Version Kernel: ')
            if i: break
        open(os.path.join(folder, 'version'), 'w').write(i)
        print ('Choose Scheduler Kernel: \n\n[1] HMP\n[2] EAS\n[3] CFS\n')
        while 1:
            i = input('Enter a Value: ')
            i = int(i)
            if i == 1 or i == 2 or i == 3: break
        w = open(os.path.join(folder, 'type'), 'w')
        w.write(['HMP', 'EAS', 'CFS'][i-1])
        w.close()

    def list(a):
        files = os.listdir(config)
        dir = []
        for name in files:
            if os.path.isdir(os.path.join(config, name)):
                dir.append(name)
        return dir

    def update(a, arg):
        dir = os.path.join(config, arg)
        print ('Editing folder %s :\n\n[1]Codename\n[2]Branch\n[3]Kernel Version\n[4]Scheduler Kernel\n' % arg)
        list = ['codename', 'branch', 'version', 'type']
        i = input('Enter Choose: ')
        i = int(i)-1
        r = open(os.path.join(dir, list[i])).read()
        print ('\nOld %s is %s \n' %(list[i], r))
        j = input('Enter new value: ')
        open(os.path.join(dir, list[i]), 'w').write(j)

    def writeConfig(a, dir, ask, conf):
        while 1:
            i = input('Enter a %s: ' % ask)
            if i: break
        w = open(os.path.join(dir, conf), 'w')
        w.write(i)
        w.close()

if __name__ == "__main__":
   Main(sys.argv[1:])
