#!/usr/bin/env bash
#
# Copyright (C) 2019 @alanndz (Telegram and Github)
# SPDX-License-Identifier: GPL-3.0-or-later
#

while (( ${#} )); do
    case ${1} in
        "-r"|"--release") shift; R=true; VERSION=${1} ;;
        "-s"|"--status") S=true ;;
        "-b"|"--branch") shift; B=true; BRANCH=${1} ;;
        "-c"|"--codename") shift; C=true; CODENAME=${1} ;;
    esac
    shift
done

CONF="${PWD}/config"

function info() {
    for i in "${@}"; do
        echo "${i}"
    done
}

#Codename
if [[ ${C} && -z ${CODENAME} ]]; then
    info "" \
         "Enter specific codename!!" \
         "" 
    exit
elif [[ ${C} && ${CODENAME} ]]; then
    echo "Codename: ${CODENAME}"
    echo "${CODENAME}" > "${CONF}/conf-codename"
fi

# Branch
if [[ ${B} && -z ${BRANCH} ]]; then
    info "" \
         "Enter specific Branch!!" \
         ""
    exit
elif [[ ${B} && ${BRANCH} ]]; then
    echo "Branch: ${BRANCH}"
    echo "${BRANCH}" > "${CONF}/conf-branch"
fi

#Release

# Status
if [[ ${S} ]]; then
    info "" \
         "Release: $(cat ${CONF}/conf-release)" \
         "Version: $(cat ${CONF}/conf-version)" \
         "Type: $(cat ${CONF}/conf-type)" \
         "Codename: $(cat ${CONF}/conf-codename)" \
         "Branch: $(cat ${CONF}/conf-branch)"
    exit
fi

## Release Write
## END ##
if [[ ${R} && -z ${VERSION} ]]; then
    info "" \
        "Enter specific version!!" \
        "example: -r/--release v1.00"
    exit
fi
if [[ ${R} ]]; then
    echo "Release: True"
    echo "1" > "${CONF}/conf-release"
    echo "${VERSION}" > "${CONF}/conf-version"
    git commit -asm "Release: Fusion $(cat "${CONF}/conf-codename") $(cat "${CONF}/conf-version")"
    exit
else
    echo "Release: False"
    echo "0" > "${CONF}/conf-release"
    git commit -asm "Switch: Back to CI"
    exit
fi

# git commit -asm "Switch: Build Fusion $(cat "${CONF}/conf-codename")"
